on:
  push:
    branches:
      - "*"
  
env:
  test_string: 'hello world'

jobs:
  # hello_world:
  #   name: hello world
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: hello world
  #     run:  echo $test_string

  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Cloning repo # This step is required
      uses: actions/checkout@v2

    - name: Publish to Sharepoint
      uses: obrassard/action-sharepoint-publish@v1.0.1
      with:
       site_url: 'https://you.sharepoint.com/sites/mySite'
       library_folder: 'Shared documents/releases'
       sharepoint_user: ${{ secrets.USER }}
       sharepoint_password: ${{ secrets.PASSWORD }}